[build]
  functions = "netlify/functions"
  publish = "_site"

[[plugins]]
package = "@quarto/netlify-plugin-quarto"

[[redirects]]
  from = "/posts.html"
  to = "https://newsletter.markgingrass.com"
  status = 301

[[redirects]]
  from = "/posts.xml"
  to = "https://newsletter.markgingrass.com"
  status = 301